Implemented unit tests over GreetingService
fland/notes-keeper pull request #1
Opened 2017-02-05 10:23 UTC by ioan994

Added Junit dependency
Added Idea and target directories to gitignore

2017-02-05 11:32 UTC, fland commented on pom.xml
> +            <version>4.12</version>
you might use maven <scope>test</scope> https://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html#Dependency_Scope

2017-02-05 11:40 UTC, fland commented on src/test/java/org/noteskeeper/server/GreetingServiceTest.java
> +        assertEquals("",expectedGreeting, service.greet(null));
you might omit empty assert message => assertEquals(expectedGreeting, service.great(null))

2017-02-05 11:41 UTC, fland requested changes

2017-02-05 11:41 UTC, fland commented on src/test/java/org/noteskeeper/server/GreetingServiceTest.java
> +        assertEquals("",expectedGreeting, service.greet("Ivan"));
use Ctrl+Alt+L in Idea for code formatting

2017-02-08 21:15 UTC, fland approved these changes

2017-02-08 21:15 UTC, merged

2017-02-08 21:57 UTC, mnovoseltsev commented on pom.xml
> +            <version>4.12</version>
Hi Guys, JUnit 5 is up and running. No sense to use 4th, http://junit.org/junit5/.

2017-02-09 09:39 UTC, fland commented on pom.xml
> +            <version>4.12</version>
there's no GA (general available) or RELEASE version yet.

2017-02-09 10:33 UTC, mnovoseltsev commented on pom.xml
> +            <version>4.12</version>
You are not writing enterprise project, why do not use latest Junit as well as try java 9 ?